create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  goal text not null,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.leads enable row level security;

create policy "service role manages users"
  on public.users for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create policy "service role manages leads"
  on public.leads for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

insert into public.users (email, password)
select 'member' || n || '@skillstack.demo',
       '5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5'
from generate_series(1, 25) as n
on conflict (email) do nothing;

insert into public.leads (name, email, goal)
select
  (array['Aarav','Diya','Kabir','Meera','Riya','Arjun','Anaya','Vihaan'])[1 + (n % 8)],
  'member' || (1 + (n % 25)) || '@skillstack.demo',
  (array['Build a portfolio','Find first client','Improve pricing','Create a brand identity','Launch a freelance service','Learn client outreach'])[1 + (n % 6)]
from generate_series(1, 60) as n;
